"""Database-side SQL script generation for cloud and Exadata targets."""

from __future__ import annotations

from pathlib import Path

from dbman_opsi.config import EnablementConfig, Target

DB_SCRIPT_TARGETS = {"dbcs", "exadata", "external-db", "external-exadata"}


def _sql_header(target: Target) -> str:
    return f"""-- Generated by dbman-opsi for target: {target.name}
-- Run as SYSDBA or an account allowed to create users and grant catalog privileges.
-- Passwords are prompted interactively and are not stored in generated files.
set echo on
set verify off
set serveroutput on
whenever sqlerror exit sql.sqlcode
"""


def _container_block(target: Target) -> str:
    default_service = target.service_name or "ORCLPDB1"
    return f"""
prompt Enter target PDB/container name. Use the target service name if unsure.
accept pdb_name char default '{default_service}' prompt 'PDB/container [{default_service}]: '

declare
  l_con_id number;
begin
  select con_id into l_con_id from v$containers where name = upper('&pdb_name');
  execute immediate 'alter session set container = ' || dbms_assert.simple_sql_name(upper('&pdb_name'));
  dbms_output.put_line('Switched to container ' || upper('&pdb_name') || ' (CON_ID=' || l_con_id || ')');
exception
  when no_data_found then
    dbms_output.put_line('Container ' || upper('&pdb_name') || ' not found; continuing in current container.');
end;
/
"""


def monitoring_user_sql(target: Target) -> str:
    user = target.monitoring_user or "DBSNMP"
    return _sql_header(target) + _container_block(target) + f"""
accept monitoring_user char default '{user}' prompt 'Monitoring user [{user}]: '
accept monitoring_password char hide prompt 'Monitoring user password: '

declare
  l_count number;
begin
  select count(*) into l_count from dba_users where username = upper('&monitoring_user');
  if l_count = 0 then
    execute immediate 'create user ' || dbms_assert.simple_sql_name(upper('&monitoring_user')) ||
      ' identified by "' || replace('&monitoring_password', '"', '""') || '" account unlock';
    dbms_output.put_line('Created monitoring user ' || upper('&monitoring_user'));
  else
    execute immediate 'alter user ' || dbms_assert.simple_sql_name(upper('&monitoring_user')) ||
      ' identified by "' || replace('&monitoring_password', '"', '""') || '" account unlock';
    dbms_output.put_line('Updated and unlocked monitoring user ' || upper('&monitoring_user'));
  end if;
end;
/
"""


def basic_grants_sql(target: Target) -> str:
    user = target.monitoring_user or "DBSNMP"
    return _sql_header(target) + _container_block(target) + f"""
accept monitoring_user char default '{user}' prompt 'Monitoring user [{user}]: '

grant create session to &monitoring_user;
grant select any dictionary to &monitoring_user;
grant select_catalog_role to &monitoring_user;

-- Public OCI Ops Insights prerequisite for cloud databases:
-- SELECT ANY DICTIONARY and SELECT_CATALOG_ROLE granted to the monitoring user.
-- Database Management uses the Basic monitoring credential for users such as DBSNMP.
"""


def advanced_grants_sql(target: Target) -> str:
    user = target.monitoring_user or "DBSNMP"
    return _sql_header(target) + _container_block(target) + f"""
accept monitoring_user char default '{user}' prompt 'Advanced diagnostics user [{user}]: '

grant analyze any to &monitoring_user;
grant analyze any dictionary to &monitoring_user;
grant execute on sys.dbms_monitor to &monitoring_user;
grant read on sys.audit_actions to &monitoring_user;
grant read on sys.v_$session to &monitoring_user;
grant read on sys.gv_$session to &monitoring_user;
grant select on sys.v_$parameter to &monitoring_user;
grant select on sys.v_$spparameter to &monitoring_user;
grant select on sys.v_$system_parameter to &monitoring_user;
grant select on sys.v_$system_parameter2 to &monitoring_user;
grant select on sys.gv_$instance to &monitoring_user;
grant select on sys.v_$rman_backup_job_details to &monitoring_user;
grant select on sys.v_$flashback_database_log to &monitoring_user;

-- Performance Hub privileges (AWR, ADDM, ASH Analytics, SQL Tuning, Real-Time
-- SQL Monitoring). The OCI Console prompt "Performance Hub requires granting of
-- appropriate user privileges" maps to exactly this set for the monitoring user.
-- These exercise the Diagnostics and/or Tuning Pack — review licensing first.
grant create procedure to &monitoring_user;
grant select any dictionary to &monitoring_user;
grant select_catalog_role to &monitoring_user;
grant alter system to &monitoring_user;
grant advisor to &monitoring_user;
grant execute on sys.dbms_workload_repository to &monitoring_user;

-- Optional advanced diagnostics grants. Review against your licensing and security policy.
-- For complete minimum and advanced Database Management credential scripts,
-- Oracle documents MOS KB57458 and KB84103 as the authoritative sources.
"""


def validation_sql(target: Target) -> str:
    user = target.monitoring_user or "DBSNMP"
    return _sql_header(target) + _container_block(target) + f"""
accept monitoring_user char default '{user}' prompt 'Monitoring user [{user}]: '

column username format a30
column account_status format a30
select username, account_status, lock_date, expiry_date
from dba_users
where username = upper('&monitoring_user');

select privilege
from dba_sys_privs
where grantee = upper('&monitoring_user')
  and privilege in (
    'CREATE SESSION', 'SELECT ANY DICTIONARY', 'ANALYZE ANY', 'ANALYZE ANY DICTIONARY',
    -- Performance Hub system privileges:
    'CREATE PROCEDURE', 'ALTER SYSTEM', 'ADVISOR')
order by privilege;

select granted_role
from dba_role_privs
where grantee = upper('&monitoring_user')
  and granted_role = 'SELECT_CATALOG_ROLE';

select owner, table_name, privilege
from dba_tab_privs
where grantee = upper('&monitoring_user')
  and owner = 'SYS'
  and table_name in (
    'DBMS_MONITOR', 'AUDIT_ACTIONS', 'V_$SESSION', 'GV_$SESSION',
    -- Performance Hub object privilege:
    'DBMS_WORKLOAD_REPOSITORY')
order by table_name, privilege;
"""


def readme_text(target: Target, config: EnablementConfig) -> str:
    return f"""# Database SQL scripts for {target.name}

Target kind: {target.kind}
Region: {config.region}

Run order:

1. `01-create-monitoring-user.sql`
2. `02-grant-basic-monitoring.sql`
3. Optional: `03-grant-advanced-diagnostics.sql`
4. `04-validate-monitoring-user.sql`

Run from SQL*Plus or SQLcl as SYSDBA or an equivalent administrative account:

```sql
sqlplus / as sysdba @01-create-monitoring-user.sql
sqlplus / as sysdba @02-grant-basic-monitoring.sql
sqlplus / as sysdba @04-validate-monitoring-user.sql
```

For DBCS and Exadata PDB targets, enter the PDB/container name that matches the service configured in `dbman-opsi`.
The generated scripts do not contain plaintext passwords.
"""


def generate_db_scripts(config: EnablementConfig, output_dir: str | Path) -> list[Path]:
    base_dir = Path(output_dir)
    base_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for target in config.targets:
        if target.kind not in DB_SCRIPT_TARGETS:
            continue
        target_dir = base_dir / target.name.replace(" ", "-").lower()
        target_dir.mkdir(parents=True, exist_ok=True)
        files = {
            "README.md": readme_text(target, config),
            "01-create-monitoring-user.sql": monitoring_user_sql(target),
            "02-grant-basic-monitoring.sql": basic_grants_sql(target),
            "03-grant-advanced-diagnostics.sql": advanced_grants_sql(target),
            "04-validate-monitoring-user.sql": validation_sql(target),
        }
        for filename, content in files.items():
            path = target_dir / filename
            path.write_text(content, encoding="utf-8")
            paths.append(path)
    return paths

