"""Generate read-only diagnostics for failed DBCS/Exadata OPSI enablement."""

from __future__ import annotations

from pathlib import Path

from dbman_opsi.config import EnablementConfig, Target

DIAGNOSTIC_TARGETS = {"dbcs", "exadata"}


def _slug(name: str) -> str:
    return name.replace(" ", "-").lower()


def _sh_value(value: str | None) -> str:
    return (value or "").replace("'", "'\"'\"'")


def oci_control_plane_script(config: EnablementConfig, target: Target) -> str:
    """Return a read-only shell script that captures OCI-side OPSI evidence."""

    resource_get = (
        'run_json "database-resource" db pluggable-database get '
        '--pluggable-database-id "$DATABASE_ID"'
        if target.database_role == "PDB"
        else 'run_json "database-resource" db database get --database-id "$DATABASE_ID"'
    )
    known_insight = ""
    if target.opsi_database_insight_id:
        known_insight = """
run_json "opsi-insight-known" opsi database-insights get --database-insight-id "$OPSI_DATABASE_INSIGHT_ID"
"""

    return f"""#!/usr/bin/env bash
# Generated by dbman-opsi for target: {target.name}
# Read-only OCI diagnostics for failed Operations Insights enablement.
set -u

PROFILE='{_sh_value(config.profile)}'
REGION='{_sh_value(target.region or config.region)}'
TENANCY_OR_COMPARTMENT='{_sh_value(config.tenancy_id or config.compartment_id)}'
COMPARTMENT_ID='{_sh_value(target.compartment_id or config.compartment_id)}'
DATABASE_ID='{_sh_value(target.resource_id)}'
PARENT_CDB_ID='{_sh_value(target.parent_cdb_id)}'
DBM_PRIVATE_ENDPOINT_ID='{_sh_value(target.private_endpoint_id)}'
OPSI_PRIVATE_ENDPOINT_ID='{_sh_value(target.opsi_private_endpoint_id)}'
OPSI_DATABASE_INSIGHT_ID='{_sh_value(target.opsi_database_insight_id)}'
PASSWORD_SECRET_ID='{_sh_value(target.password_secret_id)}'
SUBNET_ID='{_sh_value(config.network.subnet_id)}'
VCN_ID='{_sh_value(config.network.vcn_id)}'
SERVICE_NAME='{_sh_value(target.service_name)}'

OUT_DIR="${{1:-opsi-diagnostics-{_slug(target.name)}}}"
mkdir -p "$OUT_DIR"

OCI=(oci --profile "$PROFILE" --region "$REGION")

run_json() {{
  local label="$1"
  shift
  local out="$OUT_DIR/${{label}}.json"
  local err="$OUT_DIR/${{label}}.err"
  echo "== $label =="
  if "${{OCI[@]}}" "$@" --output json >"$out" 2>"$err"; then
    echo "PASS: wrote $out"
    return 0
  fi
  echo "WARN: command failed; see $err"
  return 1
}}

require_value() {{
  local label="$1"
  local value="$2"
  if [ -z "$value" ]; then
    echo "MISSING: $label"
    return 1
  fi
  echo "SET: $label"
  return 0
}}

echo "Target: {target.name}"
echo "Region: $REGION"
echo "Service: $SERVICE_NAME"
echo

require_value "COMPARTMENT_ID" "$COMPARTMENT_ID"
require_value "DATABASE_ID" "$DATABASE_ID"
require_value "SERVICE_NAME" "$SERVICE_NAME"
require_value "PASSWORD_SECRET_ID" "$PASSWORD_SECRET_ID"
require_value "DBM_PRIVATE_ENDPOINT_ID" "$DBM_PRIVATE_ENDPOINT_ID"
require_value "OPSI_PRIVATE_ENDPOINT_ID" "$OPSI_PRIVATE_ENDPOINT_ID"
echo

{resource_get}

if [ -n "$PARENT_CDB_ID" ]; then
  run_json "parent-cdb" db database get --database-id "$PARENT_CDB_ID"
fi

if [ -n "$DATABASE_ID" ]; then
  run_json "managed-database" database-management managed-database get --managed-database-id "$DATABASE_ID"
fi

if [ -n "$DBM_PRIVATE_ENDPOINT_ID" ]; then
  run_json "dbm-private-endpoint" database-management private-endpoint get --private-endpoint-id "$DBM_PRIVATE_ENDPOINT_ID"
fi

if [ -n "$OPSI_PRIVATE_ENDPOINT_ID" ]; then
  run_json "opsi-private-endpoint" opsi opsi-private-endpoint get --opsi-private-endpoint-id "$OPSI_PRIVATE_ENDPOINT_ID"
fi

if [ -n "$PASSWORD_SECRET_ID" ]; then
  run_json "vault-secret" vault secret get --secret-id "$PASSWORD_SECRET_ID"
fi

{known_insight.rstrip()}

if [ -n "$COMPARTMENT_ID" ]; then
  for state in CREATING UPDATING ACTIVE FAILED NEEDS_ATTENTION; do
    run_json "opsi-insights-${{state}}" opsi database-insights list \\
      --compartment-id "$COMPARTMENT_ID" \\
      --compartment-id-in-subtree true \\
      --lifecycle-state "$state" \\
      --all
  done
  run_json "opsi-work-requests" opsi work-request list --compartment-id "$COMPARTMENT_ID" --all
fi

if [ -n "$TENANCY_OR_COMPARTMENT" ]; then
  run_json "iam-policies" iam policy list --compartment-id "$TENANCY_OR_COMPARTMENT" --all
  if command -v grep >/dev/null 2>&1; then
    if grep -Riq "service dpd" "$OUT_DIR/iam-policies.json"; then
      echo "PASS: IAM policy text mentions service dpd"
    else
      echo "MISSING: IAM policy text does not mention service dpd"
    fi
    if grep -Riq "service operations-insights" "$OUT_DIR/iam-policies.json"; then
      echo "PASS: IAM policy text mentions service operations-insights"
    else
      echo "MISSING: IAM policy text does not mention service operations-insights"
    fi
  fi
fi

if [ -n "$SUBNET_ID" ]; then
  run_json "subnet" network subnet get --subnet-id "$SUBNET_ID"
fi

if [ -n "$VCN_ID" ] && [ -n "$COMPARTMENT_ID" ]; then
  run_json "service-gateways" network service-gateway list --compartment-id "$COMPARTMENT_ID" --vcn-id "$VCN_ID" --all
fi

cat >"$OUT_DIR/README-next-steps.txt" <<'EOF'
Review checklist:
1. database-resource.json: Database Management status should be ENABLED, not FAILED/ENABLING forever.
2. managed-database.json: database-status should be UP. DOWN often means wrong service name, blocked listener, or stale password.
3. dbm-private-endpoint.json and opsi-private-endpoint.json: lifecycle-state should be ACTIVE.
4. vault-secret.json: lifecycle-state should be ACTIVE. IAM policies must allow service dpd and service operations-insights to use/read the secret/key.
5. opsi-insights-FAILED.json and opsi-work-requests.json: look for CREATE_DATABASE_INSIGHT failures and DbcsEntityChangeWorkflowFailed details.
6. Run 01-diagnose-opsi-db-readiness.sql as SYSDBA, then 02-test-opsi-login.sql with the same credentials stored in Vault.
EOF

echo
echo "Diagnostics written to $OUT_DIR"
echo "No mutating OCI commands were issued."
"""


def db_readiness_sql(target: Target) -> str:
    user = target.monitoring_user or "DBSNMP"
    service = target.service_name or "ORCLPDB1"
    return f"""-- Generated by dbman-opsi for target: {target.name}
-- Run as SYSDBA. Read-only OPSI/DBM readiness report.
set echo on
set verify off
set serveroutput on
whenever sqlerror continue

accept pdb_name char default '{service}' prompt 'PDB/container [{service}]: '
accept monitoring_user char default '{user}' prompt 'Monitoring user [{user}]: '
accept service_name char default '{service}' prompt 'Listener service name [{service}]: '

column check_name format a42
column status format a10
column detail format a90
column name format a40
column network_name format a70
column account_status format a30
column privilege format a38
column granted_role format a30
column owner format a12
column table_name format a32

prompt Current container and database state
select sys_context('USERENV','CON_NAME') as current_container,
       open_mode,
       database_role
from v$database;

prompt Requested PDB/container state, if present
select name, open_mode, restricted
from v$pdbs
where name = upper('&pdb_name');

prompt Listener service registration visible to the database
select name, network_name, con_id
from cdb_services
where upper(name) = upper('&service_name')
   or upper(network_name) = upper('&service_name')
   or upper(name) = upper('&pdb_name')
order by con_id, name;

declare
  l_count number;
begin
  select count(*) into l_count from v$containers where name = upper('&pdb_name');
  if l_count > 0 then
    execute immediate 'alter session set container = ' || dbms_assert.simple_sql_name(upper('&pdb_name'));
    dbms_output.put_line('Switched to container ' || upper('&pdb_name'));
  else
    dbms_output.put_line('Container ' || upper('&pdb_name') || ' not found; staying in current container.');
  end if;
end;
/

prompt Monitoring account state in target container
select username, account_status, lock_date, expiry_date, common
from dba_users
where username = upper('&monitoring_user');

prompt Required system privileges
with required(privilege) as (
  select 'CREATE SESSION' from dual union all
  select 'SELECT ANY DICTIONARY' from dual union all
  select 'ANALYZE ANY' from dual union all
  select 'ANALYZE ANY DICTIONARY' from dual union all
  select 'CREATE PROCEDURE' from dual union all
  select 'ALTER SYSTEM' from dual union all
  select 'ADVISOR' from dual union all
  select 'ADMINISTER SQL TUNING SET' from dual union all
  select 'ADMINISTER ANY SQL TUNING SET' from dual
)
select r.privilege,
       case when p.privilege is null then 'MISSING' else 'OK' end as status
from required r
left join dba_sys_privs p
  on p.grantee = upper('&monitoring_user')
 and p.privilege = r.privilege
order by status desc, r.privilege;

prompt Required role grants
with required(granted_role) as (
  select 'SELECT_CATALOG_ROLE' from dual
)
select r.granted_role,
       case when p.granted_role is null then 'MISSING' else 'OK' end as status
from required r
left join dba_role_privs p
  on p.grantee = upper('&monitoring_user')
 and p.granted_role = r.granted_role
order by status desc, r.granted_role;

prompt Required object privileges
with required(owner, table_name) as (
  select 'SYS', 'DBMS_MONITOR' from dual union all
  select 'SYS', 'DBMS_WORKLOAD_REPOSITORY' from dual union all
  select 'SYS', 'V_$SESSION' from dual union all
  select 'SYS', 'GV_$SESSION' from dual union all
  select 'SYS', 'V_$PARAMETER' from dual union all
  select 'SYS', 'V_$SYSTEM_PARAMETER' from dual
)
select r.owner, r.table_name,
       case when p.table_name is null then 'MISSING' else 'OK' end as status,
       p.privilege
from required r
left join dba_tab_privs p
  on p.grantee = upper('&monitoring_user')
 and p.owner = r.owner
 and p.table_name = r.table_name
order by status desc, r.table_name;

prompt AWR/PDB autoflush state for Performance Hub and SQL Insights context
select name, value
from v$parameter
where lower(name) in ('awr_pdb_autoflush_enabled', 'control_management_pack_access');

select count(*) as awr_snapshots_for_current_container
from dba_hist_snapshot
where dbid = sys_context('USERENV', 'CON_DBID');
"""


def login_probe_sql(target: Target) -> str:
    user = target.monitoring_user or "DBSNMP"
    service = target.service_name or "ORCLPDB1"
    return f"""-- Generated by dbman-opsi for target: {target.name}
-- Run from a client that can resolve/reach the same service name OPSI uses.
-- Paste the same password stored in OCI Vault. The script does not save it.
set echo on
set verify off
whenever sqlerror exit sql.sqlcode

accept connect_identifier char default '{service}' prompt 'Connect identifier/service [{service}]: '
accept monitoring_user char default '{user}' prompt 'Monitoring user [{user}]: '
accept monitoring_password char hide prompt 'Monitoring password from Vault: '

connect &monitoring_user/"&monitoring_password"@&connect_identifier

column current_user format a30
column current_container format a30
select user as current_user,
       sys_context('USERENV','CON_NAME') as current_container
from dual;

select count(*) as can_read_v_database from v$database;
select count(*) as can_read_dba_users from dba_users;
select count(*) as can_read_gv_session from gv$session;
select count(*) as can_read_awr_snapshots from dba_hist_snapshot;

prompt PASS: monitoring login, service routing, and dictionary reads succeeded.
"""


def readme_text(target: Target) -> str:
    return f"""# OPSI diagnostics for {target.name}

These scripts are read-only and are meant to explain why Operations Insights
enablement fails after OCI-side prerequisites appear to be present.

## Run Order

1. `00-oci-control-plane-diagnostics.sh`
   - Runs OCI CLI read calls for the database, managed database, private
     endpoints, Vault secret, existing OPSI insights, recent OPSI work requests,
     IAM policies, and selected network resources.
   - Output goes to a local directory passed as the first argument.
2. `01-diagnose-opsi-db-readiness.sql`
   - Run as SYSDBA on the database server/client.
   - Checks container/service visibility, monitoring user status, grants, roles,
     object privileges, and AWR-related switches.
3. `02-test-opsi-login.sql`
   - Run from a SQL*Plus/SQLcl client that can resolve the same service name
     configured for OPSI.
   - Paste the same monitoring password stored in Vault. This catches wrong
     Vault secret values, locked/expired users, wrong PDB service names, and
     missing dictionary grants.

## Copy-Paste Commands

Run the OCI-side capture from Cloud Shell or a workstation with OCI CLI access:

```bash
./00-oci-control-plane-diagnostics.sh ./out
```

Run the SYSDBA readiness report and spool the output for review:

```sql
sqlplus / as sysdba
spool opsi-db-readiness.log
@01-diagnose-opsi-db-readiness.sql
spool off
exit
```

Run the login probe from a client that reaches the same listener/service that
DBM and OPSI use. Enter the Vault password when prompted:

```sql
sqlplus /nolog
spool opsi-login-probe.log
@02-test-opsi-login.sql
spool off
exit
```

## Fix Map

- `managed-database.json` has `database-status` other than `UP`: DBM cannot
  connect or monitor reliably. DBA/network owner should fix the service name,
  listener reachability, account state, or monitoring password first; then rerun
  DBM reconcile/enable before retrying OPSI.
- `opsi-insights-FAILED.json` or `opsi-work-requests.json` mentions
  `DbcsEntityChangeWorkflowFailed`: OCI owner should inspect the failed work
  request, and DBA should run the login probe with the Vault password to prove
  whether OPSI can authenticate and read the database.
- IAM policy output does not mention `service dpd` and `service
  operations-insights`: IAM owner should add/readjust service-principal policy
  statements so DBM/OPSI can use the Vault secret/key and private endpoint path.
- SQL login probe fails with ORA-01017/ORA-28000/ORA-28001: Vault password or
  account state is wrong. Rotate/update the Vault secret, unlock the account, or
  clear expiry, then reconcile DBM and retry OPSI.
- SQL login probe fails with ORA-12514/ORA-12154: service name/listener routing is
  wrong for the PDB/service OPSI is using. Fix `service_name` in config or DB
  listener/service registration, regenerate OPSI payloads, then retry.
- `dbm-private-endpoint.json`, `opsi-private-endpoint.json`, or
  `vault-secret.json` is not `ACTIVE`: wait for the resource or recreate/fix it
  before retrying OPSI.

After fixing the failing signal, rerun:

```bash
dbman-opsi preflight --config <config> --db-check-file opsi-db-readiness.log
dbman-opsi enable --config <config> --apply --force-reconcile
dbman-opsi validate --config <config>
```
"""


def generate_opsi_diagnostics(config: EnablementConfig, output_dir: str | Path) -> list[Path]:
    """Generate per-target OPSI diagnostic scripts and return written paths."""

    base_dir = Path(output_dir)
    base_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for target in config.targets:
        if target.kind not in DIAGNOSTIC_TARGETS or not target.wants("opsi"):
            continue
        target_dir = base_dir / _slug(target.name)
        target_dir.mkdir(parents=True, exist_ok=True)
        files = {
            "README.md": readme_text(target),
            "00-oci-control-plane-diagnostics.sh": oci_control_plane_script(config, target),
            "01-diagnose-opsi-db-readiness.sql": db_readiness_sql(target),
            "02-test-opsi-login.sql": login_probe_sql(target),
        }
        for filename, content in files.items():
            path = target_dir / filename
            path.write_text(content, encoding="utf-8")
            if filename.endswith(".sh"):
                path.chmod(0o750)
            paths.append(path)
    return paths
